---
title: "Cloning a GitHub Repository in RStudio Cloud"
author: "Matt Farrow"
date: "2019-10-01"
output: html_document
categories:
  - R
tags:
  - github
  - rstudio
lastmod: '2019-10-30T14:40:15-05:00'
publishDate: '2019-10-01'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
---

I'm working on a talk for an upcoming conference and decided I'd try and set up an [RStudio Cloud](https://rstudio.cloud) project to work it from my iPad^[I've long dreamed of an RStudio app, but with the new Safari update bringing [desktop-class browsing](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes) in iOS 13, this is a fantastic option.]. I was able to clone the repository wtihout any issue, but ran into an authentication issue when I tried to commit and push my changes back up. I knew I'd run into this issue before, so I went looking for solutions and found my answer in the wonderful [*Happy Git and GitHub for the useR*](https://happygitwithr.com).

The problem was I'd cloned the repository as HTTPS, but because my GitHub account is secured with [2FA](https://authy.com/what-is-2fa/), I needed to connect via SSH. 

1. [Generate a public key using GitHub](https://happygitwithr.com/ssh-keys.html#option-1-set-up-from-rstudio)
2. [Add the public key to GitHub](https://happygitwithr.com/ssh-keys.html#on-github)
3. [Switch remote URLs from HTTPS to SSH](https://help.github.com/en/github/using-git/changing-a-remotes-url#switching-remote-urls-from-https-to-ssh)

### Update

Ironically, I wasn't the only one who ran into this issue recently.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I finally added 2-factor authentication to GitHub, but it broke my setup with <a href="https://twitter.com/hashtag/RStudio?src=hash&amp;ref_src=twsrc%5Etfw">#RStudio</a>. But I was able to figure it out (SSH) thanks to <a href="https://twitter.com/hashtag/happygitwithR?src=hash&amp;ref_src=twsrc%5Etfw">#happygitwithR</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/hxPsOQpPLw">https://t.co/hxPsOQpPLw</a> Thanks <a href="https://twitter.com/JennyBryan?ref_src=twsrc%5Etfw">@JennyBryan</a> <a href="https://twitter.com/jimhester_?ref_src=twsrc%5Etfw">@jimhester_</a> et al!</p>&mdash; JuliaStewart Lowndes (@juliesquid) <a href="https://twitter.com/juliesquid/status/1189328972955443201?ref_src=twsrc%5Etfw">October 29, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>